### ISSUE TITLE
Compile error "Config.js not found".

### ISSUE THREAD

**Issue by crisqyxw** [Sinuslabs/Reach#16]
When I modified and try to run the "compileAndBuild.sh", I got some error messages like this:
```bash
❯ sh compileAndBuild.sh
ERROR: 1.5 is not a valid semantic version number
Making the Projucer accessible for this project
Building the plugins
Cleaning Builds but keeping the source code...
Loading the preset...Line 1, column 1: File /home/crisq/Reach/Scripts/Config.js not found {SW50ZXJmYWNlfG9uSW5pdCgpfDB8MXwx}
DONE

ERROR: No Interface found.
You have to add at least one script processor and call Synth.addToFront(true).ERROR: Export Error
The sanity check failed. Aborting export...
==============================================================================
EXPORT ERROR: The sanity check failed. Aborting export...
==============================================================================
```
I would like to ask if this is a problem with the repository itself, or am I doing something wrong? Or any suggestions on how to fix this? thanks a lot.

**Comment by oskarsh** [comment]
Hey there is indeed a config.js which is missing. This config.js needs to be created and placed into the script folder. The config needs to have a API_KEY variable which is used for authorization of the plugin. You can just leave it empty to compile the tool. 

Furthermore for the compile script to work you will need to open up the project in HISE and compile the dsp networks individually first since there is no CLI
